.pylintrc, ChangeLog, ci_setup_pypff.sh, libratom/__init__.py, libratom/utils/pff.py, requirements-dev.in, requirements-dev.txt, requirements.txt, tests/conftest.py, tests/test_libratom.py, tox.ini
Please review at your convenience, thanks.
=> Pypff wrapper class

.travis.yml, ChangeLog
The changelog also got committed (after I ran tox locally), which is fine. This file is only meaningful for official releases as it gets shipped with the release package and shows up on PyPI. Outside of official releases we can update it whenever we want, and not necessarily after each commit.
=> Add OSX to Travis

.pylintrc, README.md, libratom/cli/subcommands.py, libratom/lib/concurrency.py, libratom/lib/database.py, libratom/lib/entities.py, libratom/lib/report.py, libratom/models/__init__.py, libratom/models/entity.py, libratom/models/file_report.py, libratom/models/message.py, tests/unit/test_cli.py, tests/unit/test_libratom.py, tox.ini
This should provide a first working version of the database reports. 
If you run the ratom tool as before the resulting database file should contain additional file report data, which you can query either through the ORM in a notebook (look at the unit test code for example) or as SQL, e.g:
```SQL
sqlite> select message.* from message join file_report
...> on file_report.id = message.file_report_id
...> where file_report.path = '/tmp/libratom/test_data/RevisedEDRMv1_Complete/chris_dorland/chris_dorland_001_1_1_1.pst';
```
=> Database Reports

libratom/lib/entities.py, tests/unit/test_cli.py
This should also give us a slight bump in coverage
=> Improve session management

.gitignore, libratom/cli/subcommands.py, libratom/lib/__init__.py, libratom/lib/base.py, libratom/lib/concurrency.py, libratom/lib/core.py, libratom/lib/database.py, libratom/lib/entities.py, libratom/lib/mbox.py, libratom/lib/pff.py, tests/conftest.py, tests/unit/test_cli.py, tests/unit/test_libratom.py
More unit tests will be added as we go through use cases
=> First pass at mbox support

libratom/lib/core.py, libratom/lib/exceptions.py, tests/conftest.py, tests/unit/test_cli.py, tests/unit/test_libratom.py
More deterministic file type detection.
~~Also fixes the stalled test problem on OSX.~~
=> PST / mbox file type detection

.travis.yml, libratom/lib/download.py, requirements-dev.txt, requirements.txt, tests/conftest.py, tests/unit/test_cli.py, tests/unit/test_libratom.py, tox.ini
- Update spaCy to 2.2.1
- Update other dependencies
- Optimize how data files are downloaded
- Make the tests not timeout on travis
=> Misc. improvements

libratom/lib/report.py
=> Reduce chunk size for file report

.travis.yml
=> Perform Python 3.7 test/build jobs on Ubuntu 18.04LTS

libratom/lib/pff.py
=> Lazy build of PffArchive's internal tree

.travis.yml
=> Add OSX with xcode11.2 to test matrix

README.md
Added install and dependency instructions for Windows and macOS platforms.
=> Readme platforms

README.md
Minor fixes for clarity and consistency with naming conventions.
=> README refinements and clarifications

libratom/lib/concurrency.py, libratom/lib/mbox.py, tests/conftest.py, tests/unit/test_libratom.py
Working around the issue discussed here: https://bugs.python.org/issue27321
=> Missing CTE header use case

tests/unit/test_libratom.py
We monkey patch one of our classes to raise KeyboardInterrupt. Arguably a bit of a hack and not particularly useful, except for hitting hard to reach exception handling code.
=> Simulate CTRL-C in entity extraction test

tests/unit/test_libratom.py
Adding one unit test similar to the previous PR, which should give us a slight coverage bump.
=> Test CTRL-C during the file scan phase

.travis.yml, tox.ini
=> Add Python 3.8 to CI (#89)

libratom/data/media_types.json, tests/unit/test_scripts.py
Skip media type list validation in Travis since we don't control when IANA updates their list
=> Update media types

tests/unit/test_scripts.py
This should get us back from 93% to 96%
=> Adapt media type list validation test for coverage

requirements-dev.txt, requirements.txt, tests/unit/test_cli.py
=> updates for 0.2.4

libratom/lib/download.py, tests/conftest.py
The changes in test/conftest.py are what matters (this is where the error was happening).
The edits in libratom/lib/download.py should have no noticeable effect...
=> Work around intermittent broken connections in CI

libratom/lib/core.py
=> Update spacy model list (#110)

tests/unit/test_cli.py
Plugging some holes in our code coverage
=> Additional unit test cases

libratom/lib/core.py, requirements-dev.txt, requirements.txt
Also updated dependencies ahead of the next stable release
=> Export .eml files grouping

.pylintrc, libratom/cli/cli.py, libratom/data/__init__.py, libratom/data/media_types.json, libratom/lib/base.py, libratom/lib/concurrency.py, libratom/lib/entities.py, libratom/lib/mbox.py, libratom/lib/pff.py, libratom/models/entity.py, requirements-dev.in, requirements-dev.txt, requirements.txt, tests/unit/test_libratom.py
Comprehensive and possibly optimized MIME type detection. Known indices of attachment MIME types are cached on the PffArchive instance to speed up searches.
=> Updated attachment MIME type detection code

.travis.yml, libratom/cli/subcommands.py, libratom/lib/core.py, libratom/lib/entities.py, tests/unit/test_cli.py, tests/unit/test_libratom.py
First batch of updates to add support for transformer models
=> Transformer model support

.github/workflows/test_suite.yml
To reflect more closely what the steps do.
Also switch from test pypi to actual pypi
=> Rename workflow steps
